### ISSUE TITLE
Any plan to release checkpoints and code?

### ISSUE THREAD

**Issue by duxiaodan** [GR2-Manipulation/GR2-Manipulation.github.io#1]
Hi authors,

Congrats on the exciting new paper. I would like to know whether there's a plan to release the training code and checkpoints in the near future? Thank you in advance.

**Comment by taokong** [comment]
@duxiaodan For now, we don't have the plan to release the code and model. Thanks for your understanding. If you have any questions, please contact us via emails in the tech report.
